config/routes.rb
Rails.application.routes.draw do

  get 'index', to: 'welcome#index'
  get 'jobapp', to: 'welcome#jobapp'
  get 'contact', to: 'welcome#contact'

  get 'research', to: 'research#index'
  get 'research_awards', to: 'research#awards'
  get 'research_services', to: 'research#services'
  get 'research_scriptinspector', to: 'research#scriptinspector'
  get 'research_ssoscan', to: 'research#ssoscan'
  get 'research_explication', to: 'research#explication'
  get 'research_esorics', to: 'research#esorics'
  get 'research_httponly', to: 'research#httponly'
  get 'research_redactdom', to: 'research#redactdom'
  get 'research_unifying', to: 'research#unifying'

  get 'life', to: 'life#index'
  get 'life_family', to: 'life#family'
  get 'life_edu', to: 'life#edu'
  get 'life_sports', to: 'life#sports'
  get 'life_tcg', to: 'life#tcg'
  get 'life_travel', to: 'life#travel'
  get '/', to: 'research#scriptinspector', constraints: lambda{|request|request.env['SERVER_NAME'].match('scriptinspector.org')} 

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/life_controller.rb
class LifeController < ApplicationController
	def index
	end
	def edu
	end
	def travel
	end
	def sports
	end
	def tcg
	end
end

app/controllers/research_controller.rb
class ResearchController < ApplicationController
  def index
  end
  def awards
  end
  def services
  end
  def scriptinspector
  end
  def ssoscan
  end
  def explication
  end
  def esorics
  end
  def httponly
  end
  def unifying
  end
  def redactdom
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  protect_from_forgery with: :exception
  def index
  end
  def jobapp
  end
  def contact
  end
  def research
  end
  def life
  end
end

app/helpers/application_helper.rb
require 'socket'

module ApplicationHelper
    def full_title(page_title = '')
		base_title = "Yuchen's Home"
		if (page_title.empty?)
		    base_title
		else
		    "#{page_title} | #{base_title}"
		end
    end
    def is_Yuchen_homepage()
	if (request.env["SERVER_NAME"].match("scriptinspector.org")) then return false else return true end
	#if (request.host == "scriptinspector.org") then return false else return true end
    end
    def specfic_css(arg = '')
		base_css = ""
		if (arg.empty?)
		    base_css
		else
		    arg
		end
    end
    def has_sidebar()
    	if (params[:controller] == "research" || params[:controller] == "life")
    		return is_Yuchen_homepage()
    	end
    	return false
    end
    def conditional_wrapper(condition=false, options={}, &block)
	  options[:tag] ||= :div  
	  if condition == true
	    concat content_tag(options[:tag], capture(&block), options.delete_if{|k,v| k == :tag})
	  else
	    concat capture(&block)
	  end
	end
end

app/helpers/life_helper.rb
module LifeHelper
end

app/helpers/research_helper.rb
module ResearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div>
    Yuchen's homepage
  </div>
  <nav>
    <ul>
      <li>Last updated: April, 24th, 2015</li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Yuchen's Home", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <!--<li><%= link_to "Job Application",   jobapp_path %></li>-->
        <li><%= link_to "Research",   research_path %></li>
        <li><%= link_to "Life",   life_path %></li>
        <li><%= link_to "Contact Me", contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= specfic_css(yield(:specific_css)) %>
  <%= favicon_link_tag 'favicon.ico' %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-17176586-5', 'auto');
  ga('send', 'pageview');

  </script>
</head>
<body>
  <%= if (is_Yuchen_homepage) then render 'layouts/header' end %>
  <% conditional_wrapper(has_sidebar, :id=>"wrapper") do %>
    <div class="container">
      <%= if (has_sidebar) then render "#{params[:controller]}/left_sidebar" end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  <% end %>
  <% if (has_sidebar) %>
    <script>
      $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });
    </script>
  <% end %>
</body>
</html>

app/views/life/_left_sidebar.html.erb
<div id="sidebar-wrapper">
	<ul class="sidebar-nav">
		<li class="sidebar-brand">
			Yuchen Zhou
		</li>
		<li>
			<%= link_to "Me", life_path, :id => "index"%>
		</li>
		<li>
			<%= link_to "Education", life_edu_path, :id => "edu" %>
		</li>
		<li>
			<%= link_to "Travel Fan", life_travel_path, :id => "travel" %>
		</li>
		<li>
			<%= link_to "Sports Fan", life_sports_path, :id => "sports" %>
		</li>
		<li>
			<%= link_to "TCG Fan", life_tcg_path, :id => "tcg" %>
		</li>
		<!--<li>
			<a href="#" id = "Earlier">Earlier Projects</a>
		</li>-->
	</ul>
</div>
<script>
	var activeSelection = "<%= params[:action] %>";
	$("#"+activeSelection).addClass("selected");
	$("#"+activeSelection).attr("href", "#");
</script>

app/views/life/_work_intro.html.erb
<div class="entry">
<h1>Research Overview</h1>
<div class="medium_picture_container">
<%= image_tag("work.jpg", :class => "img-responsive") %>
<p class="imageCaption">Yuchen presenting a poster (with Longze Chen) at Oakland 13'</p>
</div>
<div class="textBlock">
	<p>My name is Yuchen Zhou, I am a senior <a href="http://www.cpe.virginia.edu/">Computer Engineering/Science</a> Ph.D student at <a href="http://www.virginia.edu/">University of Virginia</a>.</p>
	<p>Most of my Ph.D work are focused on improving the security and privacy of web application/third-party service.  My Advisor is <a href="http://www.cs.virginia.edu/~evans">Prof. David Evans</a>, and my internship mentor at Microsoft Research is <a href="http://research.microsoft.com/en-us/people/shuochen/">Dr. Shuo Chen</a>.  I have so far published five first-author papers, four of which in top-tier conferences such as <a href="http://www.ieee-security.org/TC/SP2015/">IEEE S&amp;P (Oakland)</a> and <a href="https://www.usenix.org/conference/usenixsecurity14">USENIX</a>.  For more details, please click on individual projects on the left side, or browse down the page for a brief introduction on each project.</p>
	<p class="highlightText">I am graduating in May 2015, and am looking for a job.  For future employers, you are welcome to visit my <%= link_to "job search materials", jobapp_path %> page.</p>
</div>
</div>

app/views/life/edu.html.erb
<% provide(:title, "Education") %>
<div class="singleEntry">
	<h1>School Life</h1>
	<div class="textBlock">
		<p> I went to the high school affliated to Renmin University (人大附中) for 6 years, after I spent 6 years at Zhong Guan Cun Yi Xiao for primary school. </p>
		<%= image_tag("life/RDFZ.jpg", :class => "img-responsive medium_img") %>
		<div class="imageCaption">The high school affliated to Renmin University</div>
		<p> I was lucky enough to be admitted to the best engineering university in China - Tsinghua University. Here are a few pictures with my friends there!</p>
		<div class="row vertical-align">
		    <div class="col-md-6">
		    	<%= image_tag("life/grad_thu.jpg", :class => "img-responsive") %>
		    </div>
		    <div class="col-md-6">
		    	<%= image_tag("life/thu_reunion_2010.jpg", :class => "img-responsive") %>
		    </div>
		</div>
		<div class="imageCaption">With Friends at Tsinghua University</div>
		<p> After college, I came to the University of Virginia for Ph.D studies. </p>
		<%= image_tag("life/UVa.jpg", :class => "img-responsive medium_img") %>
		<div class="imageCaption">The Rotunda at University of Virginia</div>
	</div>
</div>

app/views/life/index.html.erb
<% provide(:title, "Life") %>
<div id="page-content-wrapper">
	<div class="singleEntry">
		<h1>Yuchen says hello!</h1>
		<div class="medium_picture_container">
			<%= image_tag("life.jpg", :class => "img-responsive") %>
			<p class="imageCaption">Yuchen hiking at Mount Rainier, WA</p>
		</div>
		<div class="textBlock">
			<p>Hey there! My name is Yuchen Zhou, I was born in the beautiful city of Wuhu in Anhui province of China.  I grew up in Beijing, attending primary school, secondary school and college there.  After finishing up college, I came to the United States to pursue a Ph.D degree at University of Virginia.</p>
			<p>I love to travel to different places, play some sports and card games when I'm not working. Please click on the left side of this page to learn more!</p>
		</div>
	</div>
</div>

app/views/life/sports.html.erb
<% provide(:title, "Sports Life") %>
<div class="singleEntry">
	<h1>Let's play ball!</h1>
	<div class="textBlock">
		<%= image_tag("life/basketball.jpg", :class => "img-responsive") %>
		<div class="imageCaption">Basketball game between UVa CSSS graduate students - 2010</div>
		<p> I love to play all sorts of sports in my spare time.  Basketball is my favorite sports and I've been playing it since primary school.  I picked up the rules of baseball and American football after I came to the States and have since become a big fan of them.  Unlike most Chinese I'm not into soccer (maybe because I can't run for a long time...)</p>
		<div class="row vertical-align margTopBot">
		    <div class="col-md-6">
		    	<%= image_tag("life/nats_park1.jpg", :class => "img-responsive") %>
		    </div>
		    <div class="col-md-6">
		    	<%= image_tag("life/nats_park2.jpg", :class => "img-responsive") %>
		    </div>
		</div>
		<div class="imageCaption">Pictures taken at National's Park, go RZim go!</div>
		<p> I don't get to play softball/football a lot (they are still rather unpopular among Chinese students), but I love to play catch with my wife.  I'm a big fan of Washington Nationals and Ryan Zimmerman (who also went to UVa!) and my wife and I used to go to the Nats games a couple times each season. </p>
	</div>
</div>

app/views/life/tcg.html.erb
<% provide(:title, "Fan of Trading Card Games") %>
<div class="singleEntry">
	<h1>Trading Card Games</h1>
	<div class="row vertical-align margTopBot">
	    <div class="col-md-4 col-md-offset-1">
	    	<%= image_tag("life/mtg.png", :class => "img-responsive") %>
	    </div>
	    <div class="col-md-4 col-md-offset-2">
	    	<%= image_tag("life/hearthstone.png", :class => "img-responsive") %>
	    </div>
	</div>
	<div class="textBlock">
		<p style="margin-top:20px;"> I'm a big fan of TCGs such as Magic: The Gathering and Hearthstone. I started playing M:TG as early as 1999 when the first set of Chinese cards were introduced to the world. My favorite format is draft/sealed in M:TG and arena in Hearthstone, where players can show their 'skills' regardless of how rich they are in real life:).  The word 'skill' is quoted because sometimes you get a big bomb and can just run away with it, but that's better than getting consistently beaten by imba cards/sick non-interactive combos!</p>
		<p> My biggest strength and weakness in terms of gameplay is that I value "value" too much. If you know a bit about TCG strategies, you know what I am talking about! I would always hate to pilot a red-burn (MTG) or face-hunter (Hearthstone) deck! </p>
		<p> Because MTG is so expensive, I've even created tools for my friends and I to simulate-draft Magic booster packs online, much like the <a href="http://drafts.in">drafts.in</a> app.  My app had a better looking UI than theirs!  However, it's impossible to dedicate myself to update the app and the project has since been obsolete. </p>
	</div>
</div>

app/views/research/_left_sidebar.html.erb
<div id="sidebar-wrapper">
	<ul class="sidebar-nav">
		<li class="sidebar-brand">
			Research
		</li>
		<li>
			<%= link_to "Overview", research_path, :id => "index"%>
		</li>
		<li>
			<%= link_to "Resume", asset_path("Resume_Yuchen_Zhou_Full.pdf"), :id => "resume"%>
		</li>
		<li>
			<%= link_to "Awards, Patents, and Media", research_awards_path, :id => "awards" %>
		</li>
		<li>
			<%= link_to "Academic Services", research_services_path, :id => "services" %>
		</li>
		<li>
			<%= link_to "ScriptInspector", research_scriptinspector_path, :id => "scriptinspector" %>
		</li>
		<li>
			<%= link_to "SSOScan", research_ssoscan_path, :id => "ssoscan" %>
		</li>
		<li>
			<%= link_to "Explication", research_explication_path, :id => "explication" %>
		</li>
		<li>
			<%= link_to "ESORICS", research_esorics_path, :id => "esorics" %>
		</li>
		<li>
			<%= link_to "HTTP-Only Cookies", research_httponly_path, :id => "httponly" %>
		</li>
		<li>
			<%= link_to "Poster: RedactDOM", research_redactdom_path, :id => "redactdom" %>
		</li>
		<li>
			<%= link_to "Poster: Unifying Policies", research_unifying_path, :id => "unifying" %>
		</li>
		<!--<li>
			<a href="#" id = "Earlier">Earlier Projects</a>
		</li>-->
	</ul>
</div>
<script>
	var activeSelection = "<%= params[:action] %>";
	$("#"+activeSelection).addClass("selected");
	$("#"+activeSelection).attr("href", "#");
</script>

app/views/research/_work_intro.html.erb
<div class="entry">
<h1>Research Overview</h1>
<div class="medium_picture_container">
<%= image_tag("work.jpg", :class => "img-responsive") %>
<p class="imageCaption">Yuchen presenting a poster (with Longze Chen) at Oakland 13'</p>
</div>
<div class="textBlock">
	<p>My name is Yuchen Zhou, and I currently work at <a href="http://www.paloaltonetworks.com">Palo Alto Networks</a> as a security researcher.  I earned my Doctoral degree at <a href="http://www.virginia.edu/">University of Virginia</a>, under advisor <a href="http://www.cs.virginia.edu/~evans">Prof. David Evans</a>, with <%= link_to("dissertation", asset_path("dissertation.pdf")) %> titled: Improving Security and Privacy of Integrated Web Applications.
	<p>Most of my Ph.D work are focused on improving the security and privacy of web application/third-party service.  My internship mentor at Microsoft Research is <a href="http://research.microsoft.com/en-us/people/shuochen/">Dr. Shuo Chen</a>.  I have so far published five first-author papers, four of which in top-tier conferences such as <a href="http://www.ieee-security.org/TC/SP2015/">IEEE S&amp;P (Oakland)</a> and <a href="https://www.usenix.org/conference/usenixsecurity14">USENIX</a>.  For more details, please click on individual projects on the left side, or browse down the page for a brief introduction on each project.</p>
</div>
</div>

app/views/research/index.html.erb
<% provide(:title, "Research") %>
<div id="page-content-wrapper">
	<%= render "research/work_intro" %>

	<div class="entry">
		<h2><%= link_to "Understanding and Monitoring Embedded Web Scripts", research_scriptinspector_path %></h2>
		<%= image_tag "research/scriptinspector/overview.png", :class => "img-responsive medium_img"%>
		<p class="imageCaption"> ScriptInspector workflow overview </p>
		<div class="textBlock">
			<p>The ScriptInspector project helps web developers understand and monitor the behavior of embedded third-party JavaScripts on their websites.</p>
			<p>Our paper is to appear at Oakland (IEEE S&P) 2015', and more information can be found <%= link_to "here", research_scriptinspector_path %>.</p>
		</div>
	</div>

	<div class="entry">
		<h2><%= link_to "SSOScan: Automated Testing of Web Applications for Single Sign-On Vulnerabilities", research_ssoscan_path %></h2>
		<%= image_tag "research/ssoscan/systemStructure.png", :class => "img-responsive medium_img"%>
		<p class="imageCaption"> SSOScan workflow overview </p>
		<div class="textBlock">
			<p>SSOScan is an automated scanner of web applications for Single Sign-On vulnerabilities.  Our paper is published at the 23rd USENIX Security Symoposium (2014), and more details can be found <%= link_to "here", research_ssoscan_path %>.</p>
		</div>
	</div>

	<div class="entry">
		<h2><%= link_to "Explicating SDKs: Uncovering Assumptions Underlying Secure Authentication and Authorization", research_explication_path %></h2>
		<%= image_tag "research/explication/generalApproach.png", :class => "img-responsive medium_img"%>
		<p class="imageCaption"> Explication process overview </p>
		<div class="textBlock">
			<p>The goal of Explicating SDKs project is to systematically uncover implicit assumptions that are important to applications' security properties, this work is published at the 22nd USENIX Security Symposium (2013).  I did this project while I interned at Microsoft Research, and I had the great honor to work with two excellent researchers Shuo Chen (my mentor) and Rui Wang (my co-first author).  For more information, please click <%= link_to "here", research_explication_path %>.</p>
		</div>
	</div>

	<div class="entry">
		<h2><%= link_to "DOMinator: Protecting Private Web Content from Embedded Scripts", research_esorics_path %></h2>
		<%= image_tag "research/esorics/DOM.png", :class => "img-responsive medium_img"%>
		<p class="imageCaption"> DOMinator workflow overview </p>
		<div class="textBlock">
			<p>The goal of DOMinator is to build a browser that can enforce fine-grained access control policies for third-party JavaScripts.  This work is published at ESORICS 11'.</p>
			<p> Find more about this project <%= link_to "here", research_esorics_path %>.</p>
		</div>
	</div>

	<div class="entry">
		<h2><%= link_to "Why Aren't HTTP-only Cookies More Widely Deployed?", research_httponly_path %></h2>
		<%= image_tag "research/httponly/http-only.png", :class => "img-responsive medium_img"%>
		<p class="imageCaption"> HTTP-only Cookies deployment chronology </p>
		<div class="textBlock">
			<p>This short paper is presented at W2SP 10' (co-hosted with Oakland 10'), and I looked at the history and current status of how well HTTP-only cookies are deployed, and give some suggestions about how future security works can improve themselves to achieve a higher deploy rate.</p>
			<p> Find more about this project <%= link_to "here", research_httponly_path %>.</p>
		</div>
	</div>

	<div class="entry">
		<h2><%= link_to "[Poster] RedactDOM: Preventing Sensitive Data Leaking through Embedded Scripts", research_redactdom_path %></h2>
		<%= image_tag "research/redactdom/redactDOM.png", :class => "img-responsive medium_img"%>
		<p class="imageCaption"> RedactDOM workflow </p>
		<div class="textBlock">
			<p>The goal of RedactDOM project is to prevent sensitive data leaking through embedded scripts, and we (with Longze Chen) presented the poster in IEEE S&amp;P (Oakland) 13'.</p>
			<p> Find more about this project <%= link_to "here", research_redactdom_path %>.</p>
		</div>
	</div>

	<div class="entry">
		<h2><%= link_to "[Poster] Unifying Data Policies Across the Client and Server", research_unifying_path %></h2>
		<%= image_tag "research/unifying/unifying_policies.png", :class => "img-responsive medium_img"%>
		<p class="imageCaption"> Poster Snapshot </p>
		<div class="textBlock">
			<p> <a href="http://jburket.com/">Jonathan Burket</a> and I presented this poster at USENIX 11'; the idea is to generate annotated privacy policies automatically from server-side using <a href="http://jburket.com/GuardRails.pdf">GuardRails</a>, and enforce the access control policies at client side using the <%= link_to "DOMinator", research_esorics_path %>.</p>
			<p> Find more about this project <%= link_to "here", research_unifying_path %>.</p>
		</div>
	</div>

</div>

app/views/research/unifying.html.erb
<% provide(:title, "Research") %>
<div class="singleEntry">
	<h1 style="font-size:3em;">Unifying Data Policies Across the Client and Server</h1>
	<h2>Jonathan Burket, Jenny Cha, Austin DeVinney, Casey Mihaloew, Yuchen Zhou, David Evans</h2>
	<h2>University of Virginia</h2>
	<h3><a href="https://www.usenix.org/legacy/events/sec11/">Poster presented at USENIX Security 2011</a></h3>
	<%= image_tag "research/unifying/unifying_policies.png", :class => "img-responsive large_img"%>
	<div class="textBlock">
		<ul>
			<li>
				<div>Introduction</div>
				<p> Web application frameworks have greatly simplified web application development. Securing these applications, however, can still be difficult. A single mistake in a single line of code is often enough to leave a site vulnerable to attack. Earlier this year, we published GuardRails, a tool that helps secure Ruby on Rails applications by attaching security policies directly to sensitive data. These policies are currently enforced only on the server-side of the application, and while they successfully protect against a variety of access control and injection attack vulnerabilities, they do not easily integrate with the user interface and offer no client-side security. Our current work focuses on bridging the gap between the server and client side, such that a single set of security policies are enforced uniformly throughout the application. In this poster, we will demonstrate how this integration of policies on the server and client can be used to easily control what content can be accessed by untrusted scripts.
				</p>
			</li>
			<li>
				<div>Connection with <a href="http://www.jburket.com/GuardRails.pdf">GuardRails</a></div>
				<p>
					Developed by <a href="http://www.jburket.com">Jonathan Burket</a> et al., GuardRails is a source-to-source tool for Ruby on Rails that helps developers build secure web applications. GuardRails works by attaching security policies defined using annotations to the data model itself. GuardRails produces a version of the input application that automatically enforces the specified policies. GuardRails helps developers prevent a myriad of security problems including cross-site scripting attacks and access control violations while providing a large degree of flexibility to support a range of policies and development styles.
				</p>
				<p> This poster proposes to integrate <%= link_to "my ESORICS work", research_esorics_path%> (modified Chromium browser that may enforce access control policies on client-side, but requires server to provide those cumbersome policies) with GuardRails, a server side framework that can automatically generate the policies based on simple developers' annotations.
				</p>
			</li>
			<li>
				<div><%= link_to "Poster Abstract", asset_path("unifying_Abstract.pdf") %></div>
			</li>
			<li>
				<div><%= link_to "Full Poster PDF", asset_path("unifying_Poster.pdf") %></div>
			</li>
		</ul>
	</div>
</div>

app/views/welcome/about.html.erb
<% provide(:title, "About me") %>
<h1>About#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/index.html.erb
<% provide(:title, "Index Page") %>
<div class="margTop">
	<h1>Yuchen Zhou</h1>
	<h2>(周宇辰)</h2>
	<h3>Which Yuchen would you like to learn about?</h3>
	<div class="profile_picture_container margTop">
		<div class="row vertical-align">
	        <div class="col-xs-5">
				<%= link_to(image_tag("work.jpg", :class => "img-responsive", :onmouseover => "this.src='" + asset_path('work_hover.jpg') + "'", :onmouseout => "this.src='" + asset_path('work.jpg') + "'"), research_path) %>
	        </div>
	        <div class="col-xs-2">
	            <p style="text-align:center; font-size:30px;">or?</p>
	        </div>
	        <div class="col-xs-5">
				<%= link_to(image_tag("life.jpg", :class => "img-responsive", :onmouseover => "this.src='" + asset_path('life_hover.jpg') + "'", :onmouseout => "this.src='" + asset_path('life.jpg') + "'"),life_path) %>
	        </div>
	    </div>
	</div>
</div>

app/views/welcome/jobapp.html.erb
<% provide(:title, "Job Search") %>
<div class="singleEntry">
	<h1 style="margin-bottom:100px;">Job Search Materials</h1>
	<div class="row vertical-align margTopBot">
	    <div class="col-xs-offset-1 col-xs-2">
	    	<%= link_to(image_tag("jobapp/CV_research.png", :style => "max-width:75%;"), asset_path("jobapp/CV_research.pdf")) %>
	    </div>
	    <div class="col-xs-2">
	    	<%= link_to(image_tag("jobapp/CV_industry.png", :style => "max-width:75%;"), asset_path("jobapp/CV_industry.pdf")) %>
	    </div>
	    <div class="col-xs-2">
	    	<%= link_to(image_tag("jobapp/research_statement.png", :style => "max-width:75%;"), asset_path("jobapp/research_statement.pdf")) %>
	    </div>
	    <div class="col-xs-2">
	    	<%= link_to(image_tag("jobapp/linkedin.png", :style => "max-width:75%;"), "http://www.linkedin.com/in/yuchenzhouUVa") %>
	    </div>
	    <div class="col-xs-2">
	    	<%= link_to(image_tag("jobapp/github.png", :style => "max-width:75%;"), "https://www.github.com/Treeeater") %>
	    </div>
	</div>
	<div class="textBlock">
		<p class="noindent"> Hi future employers! </p>
		<p>My name is Yuchen Zhou and I am graduating with a Ph.D in Computer Engineering (research focusing on web application and third-party service security and privacy) from University of Virginia in May 2015.  You can find my Resume, research statement, LinkedIn and Github profile by clicking on the icons above. I prefer research-oriented industry lab positions that do security-related works to general software development positions, however, I am open to either of them as long as I'll be doing interesting things.  Please see details below: </p>
		<p><b>Research and/or Security-Related Positions: I would love to continue to do security research!</b> I do not have any specific area preferences on such positions. The particular domain that I know the best is web application and RESTful/Single Sign-On API security (please check out my <%= link_to "research projects page", research_path %>!).  I am also familiar with most basic concepts of lower-level vulnerabilities and defenses (e.g. buffer overflow, ROP, ASLR/DEP), network security and a little bit about cryptography.  Besides all of these, I am always super excited to learn more stuffs that I don't already know yet!</p>
		<p><b>General Industry/Developer Positions: </b> For general software development positions, I would rather work on web application-related areas.  Throughout the years of my Ph.D studies, I have accumulated lots of hands-on experience with JavaScript and MVC frameworks like Ruby on Rails.  I have done works to <%= link_to "understand", research_scriptinspector_path %> and <%= link_to "restrict", research_esorics_path %> third-party JavaScript behavior, and used Ruby to automate evaluation of my research tools in multiple projects.  I have also developed a small <%= link_to "Rails site", "https://www.github.com/Treeeater/Rails_MTG" %> to facilitate drafting for a trading card game as my hobby.  I will be very happy to work as a "full stack" engineer.  As a second choice, I am also open to general back end development involving C/C++, as I modified both Google's Chromium open source browser and Mozilla's Firefox browser as part of my Ph.D research, and they both are written largely in C/C++.
		<p> If you are interested in me, don't hesitate to <%= link_to "reach out", contact_path%>! </p>
		<p> Best, </p>
		<p class="noindent"> --Yuchen </p>
	</div>
</div>